const events = [
{
    id: 1,
    title: "Spine Therapy",
    category: "Yog Therapy",
    month: "January",
    date: "2026-01-10",
    time: "10:00 AM",
    venue: "Pragya Yog School",
    price: "$3,150",
    image: "https://pyshk.com/wp-content/uploads/2025/12/square-1_1_4-scaled.jpg",
    description: "A therapeutic yoga program focused on spinal alignment and holistic healing."
},
{
    id: 2,
    title: "Professional 1-1 Spinal Health Consultation with Shoaib",
    category: "Yog Therapy",
    month: "January",
    date: "2026-01-18",
    time: "11:00 AM",
    venue: "Consultation Room",
    price: "$1,200",
    image: "https://pyshk.com/wp-content/uploads/2025/12/1a.-yog-therapy-1-1-scaled-e1767409571804.jpg",
    description: "Private one-on-one spinal health consultation with Shoaib for personalized therapeutic guidance."
},
{
    id: 3,
    title: "Inversion Intensive Training 2026",
    category: "Intensive Training",
    month: "January",
    date: "2026-01-25",
    time: "09:00 AM",
    venue: "Main Yoga Hall",
    price: "$4,500",
    image: "https://pyshk.com/wp-content/uploads/2025/12/square-1_1_-1-scaled.jpg",
    description: "Master inversions safely. Build strength, balance, and core stability in this intensive workshop."
},
{
    id: 4,
    title: "Celebrate the Year of the Horse with the Meditative Art of Calligraphy",
    category: "Pragya Events",
    month: "February",
    date: "2026-02-08",
    time: "02:00 PM",
    venue: "Creative Studio",
    price: "$388",
    image: "https://pyshk.com/wp-content/uploads/2025/12/3.-cny-celebration-scaled.jpg",
    description: "An immersive workshop exploring the meditative flow and art of traditional Chinese calligraphy."
},
{
    id: 5,
    title: "20-Hr CET Hands-on Adjustment",
    category: "Teacher Training",
    month: "February",
    date: "2026-02-20",
    time: "09:00 AM",
    venue: "Training Hall",
    price: "$8,725",
    image: "https://pyshk.com/wp-content/uploads/2025/12/square-1_1_5-1-scaled.jpg",
    description: "Continuing education training focusing on hands-on adjustments, alignment, and assist techniques."
},
{
    id: 6,
    title: "Holi Celebration",
    category: "Pragya Events",
    month: "March",
    date: "2026-03-14",
    time: "04:00 PM",
    venue: "Campus Ground",
    price: "$400-$500",
    image: "https://pyshk.com/wp-content/uploads/2025/12/5.-holi-scaled.jpg",
    description: "Celebrate the festival of colors with yoga, music, organic colors, and delicious festive treats."
},
{
    id: 7,
    title: "Spring Rejuvenation Retreat: Yog & Ski in Niseko, Japan",
    category: "Retreat",
    month: "March",
    date: "2026-03-22",
    time: "08:00 AM",
    venue: "Niseko, Japan",
    price: "$18,960-$24,500",
    image: "https://pyshk.com/wp-content/uploads/2024/11/6.-japan-scaled.jpg",
    description: "A unique retreat combining daily yoga, meditation, and skiing in the beautiful snowscape of Niseko."
},
{
    id: 8,
    title: "ABC Workshop – Sun Salutation",
    category: "ABC Workshop",
    month: "March",
    date: "2026-03-29",
    time: "09:00 AM",
    venue: "Yoga Studio",
    price: "$1,980",
    image: "https://pyshk.com/wp-content/uploads/2026/01/7.-sun-salutation-scaled.jpg",
    description: "Break down the movements of Surya Namaskar (Sun Salutation) for a stronger daily practice."
},
{
    id: 9,
    title: "Pragya 200 – Intensive Training",
    category: "Teacher Training",
    month: "April",
    date: "2026-04-05",
    time: "09:00 AM",
    venue: "Training Center",
    price: "$515-$7,300",
    image: "https://pyshk.com/wp-content/uploads/2024/11/TTC01.jpg",
    description: "Kickstart your teacher training journey with this comprehensive intensive foundation module."
},
{
    id: 10,
    title: "Pragya 200 – Full Training",
    category: "Teacher Training",
    month: "April",
    date: "2026-04-15",
    time: "09:00 AM",
    venue: "Training Center",
    price: "$38,000",
    image: "https://pyshk.com/wp-content/uploads/2024/07/8.-200ttc-scaled.jpg",
    description: "The complete 200-Hour Registered Yoga Teacher Training program covering all aspects of classical yoga."
},
{
    id: 11,
    title: "New Moon Flow: Grounding Evening Practice",
    category: "Workshop",
    month: "May",
    date: "2026-05-18",
    time: "06:30 PM",
    venue: "Meditation Hall",
    price: "$250-$280",
    image: "https://pyshk.com/wp-content/uploads/2026/04/PYS-IG-New-Moon-Flow-Event.png",
    description: "Align with the lunar cycle. A grounding, meditative evening flow to release and set new intentions."
},
{
    id: 12,
    title: "Pragya Satsang : Concept Of Sankhya",
    category: "Teacher Training",
    month: "June",
    date: "2026-06-13",
    time: "05:00 PM",
    venue: "Satsang Hall",
    price: "$850-$1,550",
    image: "https://pyshk.com/wp-content/uploads/2025/01/Copy-of-Pragya-SatsangDr-01-e1766118083112.jpg",
    description: "An enriching Satsang session exploring the classical philosophy and concept of Sankhya."
},
{
    id: 13,
    title: "ABC Workshop: Inversions for Beginners",
    category: "ABC Workshop",
    month: "June",
    date: "2026-06-28",
    time: "09:00 AM",
    venue: "Yoga Studio",
    price: "$1,980",
    image: "https://pyshk.com/wp-content/uploads/2025/12/square-1_1_7-scaled.jpg",
    description: "Learn the fundamentals of headstands and forearm stands in a safe, guided setting."
},
{
    id: 14,
    title: "Kids Summer Yog Camp (Age 7–11 Batch 2)",
    category: "Kids Program",
    month: "July",
    date: "2026-07-06",
    time: "09:00 AM",
    venue: "Kids Hall",
    price: "$3,600",
    image: "https://pyshk.com/wp-content/uploads/2026/06/Screenshot-2026-06-19-at-11.31.16-PM.webp",
    description: "A fun-filled, educational summer camp batch 2 for kids aged 7-11 to explore movement and mindfulness."
},
{
    id: 15,
    title: "ABC Workshop: Backbends for Beginners",
    category: "ABC Workshop",
    month: "July",
    date: "2026-07-18",
    time: "09:00 AM",
    venue: "Yoga Studio",
    price: "$1,980",
    image: "https://pyshk.com/wp-content/uploads/2025/12/12.-ABC-backbends-scaled.jpg",
    description: "Demystify backbends. Learn active engagements to open the chest, shoulders, and hips safely."
},
{
    id: 16,
    title: "Sunset Beach Yog 2026",
    category: "Pragya Events",
    month: "August",
    date: "2026-08-01",
    time: "05:30 PM",
    venue: "South Bay Beach, Repulse Bay",
    price: "$400-$500",
    image: "https://pyshk.com/wp-content/uploads/2026/07/August-2026.webp",
    description: "An outdoor yoga session by the ocean followed by a guided deep relaxation under the stars."
},
{
    id: 17,
    title: "Kids Summer Yog Camp (Age 7–11 Batch 1)",
    category: "Kids Program",
    month: "August",
    date: "2026-08-03",
    time: "10:00 AM",
    venue: "Kids Hall",
    price: "$3,600",
    image: "https://pyshk.com/wp-content/uploads/2026/06/Screenshot-2026-06-19-at-11.31.05-PM.webp",
    description: "A fun-filled, educational summer camp batch 1 for kids aged 7-11 focusing on posture, core strength, and concentration."
},
{
    id: 18,
    title: "Kids Summer Yog Camp (Age 3–6)",
    category: "Kids Program",
    month: "August",
    date: "2026-08-10",
    time: "10:00 AM",
    venue: "Kids Hall",
    price: "$3,600",
    image: "https://pyshk.com/wp-content/uploads/2025/12/Screenshot-2026-06-19-at-11.34.49-PM.webp",
    description: "Gentle movement, storytelling, and sensory mindfulness play designed specifically for early learners."
},
{
    id: 19,
    title: "Kids Summer Yog Camp (Age 12–16)",
    category: "Kids Program",
    month: "August",
    date: "2026-08-17",
    time: "10:00 AM",
    venue: "Kids Hall",
    price: "$3,600",
    image: "https://pyshk.com/wp-content/uploads/2026/06/Screenshot-2026-06-19-at-11.35.22-PM.webp",
    description: "Mindfulness and yoga camp tailored for teenagers to build physical strength, emotional resilience, and focus."
},
{
    id: 20,
    title: "Back Bend Intensive Series – Part 1",
    category: "Intensive Training",
    month: "August",
    date: "2026-08-24",
    time: "09:00 AM",
    venue: "Main Yoga Hall",
    price: "$495-$6,500",
    image: "https://pyshk.com/wp-content/uploads/2025/12/15.-BBI-1-scaled.jpg",
    description: "An intensive progressive training designed to deepen spinal flexibility and alignment."
},
{
    id: 21,
    title: "Pragya Boat Trip 3.0",
    category: "Pragya Events",
    month: "September",
    date: "2026-09-12",
    time: "09:00 AM",
    venue: "Central Pier 9",
    price: "$1,350",
    image: "https://pyshk.com/wp-content/uploads/2025/12/16.boat-trip-scaled.jpg",
    description: "A beautiful day out at sea featuring sunset yoga, meditation, vegetarian lunch, and community bonding."
},
{
    id: 22,
    title: "Sacred Soundscapes",
    category: "Teacher Training",
    month: "September",
    date: "2026-09-26",
    time: "05:00 PM",
    venue: "Satsang Hall",
    price: "$10,750",
    image: "https://pyshk.com/wp-content/uploads/2025/12/17.-30-hr-mantra-sound-scaled.jpg",
    description: "Immerse yourself in sacred chants, kirtan, and sound healing frequencies to align energy."
},
{
    id: 23,
    title: "Sacred Serenity Nepal Retreat",
    category: "Retreat",
    month: "October",
    date: "2026-10-10",
    time: "08:00 AM",
    venue: "Kathmandu, Nepal",
    price: "$15,660-$19,125",
    image: "https://pyshk.com/wp-content/uploads/2025/12/18.-nepal-scaled.jpg",
    description: "A spiritual pilgrimage retreat featuring yoga, meditation, visiting sacred temples and hiking in the Himalayas."
},
{
    id: 24,
    title: "ABC Workshop: To Be Announced",
    category: "ABC Workshop",
    month: "October",
    date: "2026-10-20",
    time: "09:00 AM",
    venue: "Yoga Studio",
    price: "$1,980",
    image: "https://pyshk.com/wp-content/uploads/2024/06/team_0000_aarya.jpg",
    description: "A specialized monthly workshop focusing on key topics, to be announced soon."
},
{
    id: 25,
    title: "Nature And Hike",
    category: "Pragya Events",
    month: "October",
    date: "2026-10-31",
    time: "08:00 AM",
    venue: "Lantau Trail",
    price: "$400-$500",
    image: "https://pyshk.com/wp-content/uploads/2025/12/20.-hike-scaled.jpg",
    description: "A mindful outdoor hike connecting with nature, breathing exercises, and meditation in the forest."
},
{
    id: 26,
    title: "Back Bend Intensive Series – Part 2",
    category: "Intensive Training",
    month: "December",
    date: "2026-12-12",
    time: "09:00 AM",
    venue: "Main Yoga Hall",
    price: "$495-$5,525",
    image: "https://pyshk.com/wp-content/uploads/2025/12/22.-BBI-2-scaled.jpg",
    description: "Part 2 of the intensive backbending workshop series focusing on advanced extensions and chest opening."
},
{
    id: 27,
    title: "Christmas Festival of Inner Light",
    category: "Pragya Events",
    month: "December",
    date: "2026-12-25",
    time: "04:00 PM",
    venue: "Main Auditorium",
    price: "$400",
    image: "https://pyshk.com/wp-content/uploads/2025/12/23.-Christmas-scaled.jpg",
}
];

if (typeof window !== 'undefined') { window.events = events; }